FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  cmake \
  curl \
  g++ \
  pkg-config \
  git \
  vim-common \
  libwebsockets-dev \
  libjson-c-dev \
  libssl-dev \
  sudo \
  systemd \
  openjdk-8-jdk \
  maven \
  python \
  python3 \ 
  python-pip \
&& rm -rf /var/lib/apt/lists/*

RUN curl -sL https://ibm.biz/idt-installer | bash
RUN ibmcloud plugin install event-streams
RUN git clone https://github.com/tsl0922/ttyd.git
RUN cd ttyd && mkdir build && cd build && cmake .. && make && make install
EXPOSE 7681

ENV HELM_VERSION="v3.1.1"
RUN curl -sl https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O \
    && tar -xzf helm-${HELM_VERSION}-linux-amd64.tar.gz \
    && mv linux-amd64/helm /usr/local/bin/helm \
    && chmod +x /usr/local/bin/helm \
    && rm -f helm-${HELM_VERSION}-linux-amd64.tar.gz \
    && rm -rf linux-amd64

RUN curl -LO https://s3.amazonaws.com/chartmuseum/release/latest/bin/linux/amd64/chartmuseum \
    && chmod +x ./chartmuseum \
    && mv ./chartmuseum /usr/local/bin

CMD ["ttyd", "-p", "7681", "bash"]




